name: Build and Publish
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
        
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'
          
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
        
      - name: Build
        run: ./gradlew build
        
      - name: Upload build artifacts
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
        
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*.jar
          name: "Gentle Stripping ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Publish to Modrinth
        if: startsWith(github.ref, 'refs/tags/v')
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: "gentle-stripping"
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          
          files: build/libs/*.jar
          name: "Gentle Stripping ${{ github.ref_name }}"
          version: ${{ github.ref_name }}
          version-type: release
          
          loaders: fabric
          game-versions: |
            1.20
            1.20.1
            1.20.2
            1.20.3
            1.20.4
            1.20.5
            1.20.6
            
          dependencies: |
            fabric-api | depends
            cloth-config | optional
            modmenu | optional